language: node_js
node_js:
  - "5"
before_script:
  - npm run coverage
after_script:
  - npm run codeclimate
notifications:
  slack:
    rooms:
      weirdunicorn:zYbooEy22vfBloHorKZV5XPE#development
    on_success: change
